lib-$(CONFIG_DEBUG_UART) += uart/uart.o
lib-$(CONFIG_UART_IMX) += uart/imx-uart.o
lib-$(CONFIG_UART_MTK) += uart/mtk-uart.o
lib-$(CONFIG_UART_QCOM) += uart/qcom-uart.o
lib-$(CONFIG_UART_VIRT) += uart/virt-uart.o
